image: node:20  # Use official Node.js image

stages:
  - install
  - snyk-security
  - lint
  - test
  - build
  - deploy

variables:
  NODE_ENV: 'production'
  DATABASE_URL: "postgresql://$DB_USER:$DB_PASS@$DB_HOST:5432/$DB_NAME"

cache:
  paths:
    - node_modules/

before_script:
  - npm install -g sequelize-cli jest snyk # Ensure Jest is installed globally

install_backend:
  stage: install
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/node_modules/

install_frontend:
  stage: install
  script:
    - cd frontend
    - npm install
  artifacts:
    paths:
      - frontend/node_modules/

snyk_security_scan:
  stage: snyk-security
  script:
    - snyk auth $SNYK_AUTH_TOKEN
    - cd backend && snyk test  
    - cd ../frontend && snyk test || true 
  only:
    - main

test_backend:
  stage: test
  script:
    - npm install --save-dev jest
    - cd backend
    - npm test

build_frontend:
  stage: build
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

deploy_frontend:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying frontend..."
    # Add actual deployment command (e.g., Vercel, Netlify, AWS S3)
 
# Deploy Backend (Modify as Needed)
deploy_backend:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying backend..."
    # Add actual deployment command (e.g., Heroku, DigitalOcean, AWS)